version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./raw:/raw_data

  data-analysis-app:
    build:
      context: ./app
    volumes:
      - ./app:/app
      - ./result:/result_data
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://username:password@postgres:5432/database

volumes:
  pg_data:
