version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  init_sql:
    build:
      context: ./init_sql
    depends_on:
      - db

  app:
    build:
      context: ./app
    depends_on:
      - db
    command: python app.py

volumes:
  pgdata: